### ISSUE TITLE
The container name "/docker-instance" is already in use by container "..."

### ISSUE THREAD

**Issue by markvaneijk** [spatie/docker#10]
When seting up the Docker container within the setUp method of my TestCase in Laravel (a fresh and newly installed one). I can't get the destruct option to work for me:

```php
public function setUp(): void
{
    parent::setUp();

    $this->container = DockerContainer::create('markvaneijk/docker')
        ->name('docker-instance')
        ->mapPort(4848, 22)
        ->stopOnDestruct()
        ->start();
}
```

When running PHPUnit I get:

> Spatie\Docker\Exceptions\CouldNotStartDockerContainer: Could not start docker container for image markvaneijk/docker`. Process output: `docker: Error response from daemon: Conflict. The container name "/docker-instance" is already in use by container "0c9ff467ca3be1ddcabf085c025f957c6ee268cc8a2e0b20362f798e3205eadb". You have to remove (or rename) that container to be able to reuse that name.

I also tried putting this inside the test itself, but than I get the same error.

But it does work when I start and stop the container inside every test, so it seems like the destruct does not work as expected. Or did I forgot something to take care off?

**Comment by gnomejodas** [comment]
1. You still need to stop a container to be destroyed (removed) by the "stopOnDestruct()" method.
2. You cannot run 2 containers with the same name in docker.
3. The solution for you is a way to dinamically generate names for your containers or stop the one you have running before creating another by the same name.

**Comment by markvaneijk** [comment]
> 1. You still need to stop a container to be destroyed (removed) by the "stopOnDestruct()" method.

Why is that? It suppose it's called 'stopOnDestruct' for a reason right?

**Comment by rubenvanassche** [comment]
Hi @markvaneijk,

We stop the docker containers when an object is destructed but it seems that PHPUnit does not call the destructor each time a test finishes. Running the stop command in the `teardown` function of your test also doesn't work. I guess because docker takes some time for stopping the container and PHPunit moves on. What worked for me is creating a container from scratch in each test (be sure there are no running containers anymore running from failed tests by using `docker ps`). I've added a test beneath that works, I would recommend the factory pattern to keep the boilerplate code as minimal as possible.

```php
<?php

namespace Tests\Unit;

use Spatie\Docker\DockerContainer;
use Spatie\Docker\DockerContainerInstance;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        DockerContainerInstance::macro('whoAmI', function () {
            /** @var \Symfony\Component\Process\Process $process */
            $process = $this->execute('whoami');

            return trim($process->getOutput());
        });

        DockerContainerInstance::macro('pwd', function () {
            /** @var \Symfony\Component\Process\Process $process */
            $process = $this->execute('pwd');

            return trim($process->getOutput());
        });

        DockerContainerInstance::macro('echo', function () {
            /** @var \Symfony\Component\Process\Process $process */
            $process = $this->execute("echo 'test'");

            return trim($process->getOutput());
        });
    }

    /** @test */
    public function whoAmI()
    {
        $container = DockerContainer::create('spatie/docker')
            ->name('docker-instance')
            ->mapPort(4848, 22)
            ->stopOnDestruct()
            ->start();

        $this->assertEquals('root', $container->whoAmI());
    }


    /** @test */
    public function pwd()
    {
        $container = DockerContainer::create('spatie/docker')
            ->name('docker-instance')
            ->mapPort(4848, 22)
            ->stopOnDestruct()
            ->start();

        $this->assertEquals('/', $container->pwd());
    }

    /** @test */
    public function echo()
    {
        $container = DockerContainer::create('spatie/docker')
            ->name('docker-instance')
            ->mapPort(4848, 22)
            ->stopOnDestruct()
            ->start();

        $this->assertEquals('test', $container->echo());
    }
}
```

I will close this issue for now

**Comment by markvaneijk** [comment]
Thanks for your answer Ruben! In my own current solution I needed to stop the container, but will check this out if I can do it like this.
