### ISSUE TITLE
Request: A convenient way to get the docker instance at any time

### ISSUE THREAD

**Issue by Galironfydar** [spatie/docker#13]
So all of the `DockerContainerInstance` methods are available after you create a `DockerContainer` by accessing the instance. Should there be a way to find the docker container at any time?

My use case would be saving the docker container name within a DB then after a period of time "find" that container again then perform `->execute()` or `->stop()`.

Have i missed something? Could I use the DockerContainerInstance to get that container again already?

**Comment by freekmurze** [comment]
> Should there be a way to find the docker container at any time? 

Currently we don't offer this feature, but I'm open for PRs that add functionality.

**Comment by m7mdcc** [comment]
is this still not available ?

**Comment by rubenvanassche** [comment]
You can always send in a PR adding this.
