### ISSUE TITLE
Issue with unescaped ENV variables when calling `execute`

### ISSUE THREAD

**Issue by Patabugen** [spatie/docker#31]
Because of the way this library echos and pipes commands into docker, using environment variables with `execute` gives unexpected behaviour.

For example this does not echo 'some-value' but an empty string, because $MY_VARIABLE is evaluated on my host, and not in the container.

```
$container = DockerContainer::create('image-name')
    ->setEnvironmentVariable('MY_VARIABLE', 'some-value')
    ->start();

$process = $container->execute('echo $MY_VARIABLE');
echo $process->getOutput(); // returns ''
```

Escaping the $ before MY_VARIABLE makes it work as you'd expect (being evaluated in the container).

I think the answer is a simple:

`$command = escapeshellcmd($command);`

in `DockerContainer::getExecCommand();` before:

https://github.com/spatie/docker/blob/b88b35bc285c509707b9e3c945ad181a20c902a6/src/DockerContainer.php#L191

Happy to send a PR if that sounds correct - there's a risk of it being a breaking change if somebody is already working around the problem by escaping their `execute()` arguments though.

**Comment by freekmurze** [comment]
Thanks for having researched this.

Do send a PR for this, it seems like the right behaviour.
