### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by makhweb** [spatie/docker#6]
Does this package support Windows? 

(Sorry for the stupid question😢)

**Comment by freekmurze** [comment]
It's not a stupid question. 👍 

I'm not a windows user myself, so haven't tested it out. I would think it should work. If it doesn't (and if it's easy to fix) feel free to send a PR.

**Comment by sero583** [comment]
If you are still interested in this case, you should read my experience in [this ](https://github.com/symfony/symfony/issues/46464#issue-1249866019) issue. Spoiler: It doesn't work, due to Symfony Process not supporting/failing to execute WSL commands.
